# Simple workflow for deploying static content to GitHub Pages
name: mabl Simple Example

on:
  push:
    branches: ["main"]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: mabl Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Functional test deployment
        id: mabl-test-deployment
        uses: mablhq/github-run-tests-action@v1.4
        env:
          # Use a "CI/CD Integration" type of mabl API key
          MABL_API_KEY: ${{ secrets.MABL_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          application-id: z7L7jZU6WTVG4KjRLC7abQ-a
          environment-id: smbFvfhb0OrbyPSzVAusvw-e
        
